  rnd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: rnd-elasticsearch
    restart: on-failure
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
