version: "3.8"

services:
  rnd-vault:
    image: vault:latest
    container_name: rnd-vault
    platform: linux/arm64
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_ADDR=0.0.0.0:8200
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"